package resourcetype

// dome9 Types
const (
	CloudAccountAlibaba                          = "dome9_cloudaccount_alibaba"
	CloudAccountAWS                              = "dome9_cloudaccount_aws"
	CloudAccountAzure                            = "dome9_cloudaccount_azure"
	CloudAccountGCP                              = "dome9_cloudaccount_gcp"
	CloudAccountOCI                              = "dome9_cloudaccount_oci"
	CloudAccountOCITempData                      = "dome9_cloudaccount_oci_temp_data"
	CloudAccountKubernetes                       = "dome9_cloudaccount_kubernetes"
	IPList                                       = "dome9_iplist"
	ContinuousCompliancePolicy                   = "dome9_continuous_compliance_policy"
	ContinuousComplianceNotification             = "dome9_continuous_compliance_notification"
	RuleSet                                      = "dome9_ruleset"
	CloudAccountAWSSecurityGroup                 = "dome9_aws_security_group"
	CloudAccountAWSSecurityGroupRule             = "dome9_cloud_security_group_rule"
	Role                                         = "dome9_role"
	OrganizationalUnit                           = "dome9_organizational_unit"
	CloudAccountAzureSecurityGroup               = "dome9_azure_security_group"
	AttachIAMSafeToAwsCloudAccount               = "dome9_attach_iam_safe"
	User                                         = "dome9_user"
	IAMSafeEntity                                = "dome9_iam_safe_entity"
	ServiceAccount                               = "dome9_service_account"
	AwsUnifiedOnboardingUpdateVersionStackConfig = "dome9_aws_unified_onboarding_update_version_stack_config"
	AwsUnifiedOnboarding                         = "dome9_aws_unified_onboarding"
	AdmissionControlPolicy                       = "dome9_admission_control_policy"
	Assessment                                   = "dome9_assessment"
	ImageAssurancePolicy                         = "dome9_image_assurance_policy"
	AwpAwsOnboardingData                         = "dome9_awp_aws_onboarding_data"
	AwpAwsOnboarding                             = "dome9_awp_aws_onboarding"
	AWSOrganizationOnboarding                    = "dome9_aws_organization_onboarding"
	AWSOrganizationOnboardingManagementStack     = "dome9_aws_organization_onboarding_management_stack"
	AWSOrganizationOnboardingMemberAccountConfig = "dome9_aws_organization_onboarding_member_account_configuration"
)
